### ISSUE TITLE
Lab report 2 feedback

### ISSUE THREAD

**Issue by daniel-n-ryu** [apollolarragoitia/cse15l-lab-reports#2]
**Bug/Input 1**
- [ ] Commit screenshot for bug/input 1
  - In github, you can click on a commit made to view the code changes for the bug encountered. Please provide a screenshot of these commits/bug fixes
- [x] Link to test file for bug/input 1
- [x] Symptom shown as command + output for bug/input 1
- [x] Description of relationship between bug, symptom, and input for bug/input 1

**Bug/Input 2**
- [ ] Commit screenshot for bug/input 2
  - See bug 1
- [x] Link to test file for bug/input 2
- [x] Symptom shown as command + output for bug/input 2
- [x] Description of relationship between bug, symptom, and input for bug/input 2

**Bug/Input 3**
- [ ] Commit screenshot for bug/input 3
  - See bug 1
- [x] Link to test file for bug/input 3
- [x] Symptom shown as command + output for bug/input 3
- [x] Description of relationship between bug, symptom, and input for bug/input 3

Additional comments from your grader:
Everything is good, except it appears to the reader that these bugs were not fixed and no commit screenshot is given for any of these bugs. Please change the language of the description to demonstrate confidence in your solution and provide commit screenshots

Feel free to comment below if you have any questions about the rubric/feedback.

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by apollolarragoitia** [comment]
Hi, for a commit screenshot, would I have a screenshot with the commit history, or a screenshot of the commit including the code?Thank you.
