### ISSUE TITLE
lab report 4 feedback

### ISSUE THREAD

**Issue by daniel-n-ryu** [apollolarragoitia/cse15l-lab-reports#4]
Here is your feedback for Lab Report 4:

- [x] Provides link to their markdown-parse repository 
  - Missing
- [x] Provides link to the markdown-parse repository they reviewed
  - Missing
Snippet 1

- [ ] Shows the test(s) / expected output in MarkdownParseTest.java
  - Expected output not shown. No functional markdown link provided to expected output either (need one or the other, not both)
- [x] Shows the output of running test(s) for their implementation 
- [x] Shows the output of running for the implementation they reviewed
- [ ] Answers the code change question about their program
  - Missing
Snippet 2

- [ ] Shows the test(s) / expected output in MarkdownParseTest.java
  - Expected output not shown. No functional markdown link provided to expected output either (need one or the other, not both)
- [x] Shows the output of running test(s) for their implementation 
- [x] Shows the output of running for the implementation they reviewed
- [ ] Answers the code change question about their program
  - Missing
  
Snippet 3

- [ ] Shows the test(s) / expected output in MarkdownParseTest.java
  - Expected output not shown. No functional markdown link provided to expected output either (need one or the other, not both)
- [x] Shows the output of running test(s) for their implementation 
- [x] Shows the output of running for the implementation they reviewed
- [ ] Answers the code change question about their program
  - Missing
  
Additional comments from your grader:
Mostly just incomplete, everything else looks good though

Feel free to comment below any questions about the rubric/feedback

**Comment by apollolarragoitia** [comment]
Hi, how can I show the expected output? The photos I provided showed the expect output in the JUnit error feedback. For the expected output, would you like to see the expected output in the Junit test itself?

**Comment by daniel-n-ryu** [comment]
what you did was good enough
